package io.github.effiban.scala2java.entities

object TermNameValues {

  final val Future = "Future"
  final val Either = "Either"
  final val LowercaseRight = "right"
  final val LowercaseLeft = "left"
  final val Stream = "Stream"
  final val List = "List"
  final val Seq = "Seq"
  final val Set = "Set"
  final val Map = "Map"
  final val Try = "Try"
  final val Apply = "apply"
  final val Empty = "empty"
  final val Util = "util"

  final val ScalaRange = "Range"
  final val ScalaInclusive = "inclusive"
  final val ScalaOption = "Option"
  final val ScalaSome = "Some"
  final val ScalaNone = "None"
  final val ScalaRight = "Right"
  final val ScalaLeft = "Left"
  final val ScalaSuccess = "Success"
  final val ScalaFailure = "Failure"
  final val ScalaSuccessful = "successful"
  final val ScalaFailed = "failed"
  final val ScalaArray = "Array"
  final val ScalaVector = "Vector"
  final val ScalaNil = "Nil"

  final val Java = "java"
  final val JavaIntStream = "IntStream"
  final val JavaRange = "range"
  final val JavaRangeClosed = "rangeClosed"
  final val JavaCompletableFuture = "CompletableFuture"
  final val JavaSupplyAsync = "supplyAsync"
  final val JavaCompletedFuture = "completedFuture"
  final val JavaFailedFuture = "failedFuture"
  final val JavaOptional = "Optional"
  final val JavaAbsent = "absent"
  final val JavaOf = "of"
  final val JavaOfNullable = "ofNullable"
  final val JavaOfEntries = "ofEntries"
  final val JavaOfSupplier = "ofSupplier"
  final val JavaSuccess = "success"
  final val JavaFailure = "failure"
}