package io.github.effiban.scala2java.core.entities

object TermNameValues {

  final val Future = "Future"
  final val Either = "Either"
  final val LowercaseRight = "right"
  final val LowercaseLeft = "left"
  final val Stream = "Stream"
  final val List = "List"
  final val Seq = "Seq"
  final val Set = "Set"
  final val Map = "Map"
  final val Try = "Try"
  final val Apply = "apply"
  final val Empty = "empty"
  final val Util = "util"

  final val Plus = "+"
  final val Minus = "-"
  final val Multiply = "*"
  final val Divide = "/"
  final val Modulus = "%"

  final val And = "&&"
  final val Or = "||"

  final val BitwiseAnd = "&"
  final val BitwiseOr = "|"
  final val BitwiseXor = "^"

  final val Equals = "=="
  final val NotEquals = "!="
  final val GreaterThan = ">"
  final val GreaterEquals = ">="
  final val LessThan = "<"
  final val LessEquals = "<="

  final val AndThen = "andThen"
  final val Compose = "compose"
  final val Get = "get"
  final val Print = "print"
  final val Println = "println"

  final val ScalaRange = "Range"
  final val ScalaInclusive = "inclusive"
  final val ScalaOption = "Option"
  final val ScalaSome = "Some"
  final val ScalaNone = "None"
  final val ScalaRight = "Right"
  final val ScalaLeft = "Left"
  final val ScalaSuccess = "Success"
  final val ScalaFailure = "Failure"
  final val ScalaSuccessful = "successful"
  final val ScalaFailed = "failed"
  final val ScalaArray = "Array"
  final val ScalaVector = "Vector"
  final val ScalaNil = "Nil"
  final val ScalaTo = "to"
  final val ScalaUntil = "until"
  final val ScalaAssociate = "->"

  final val Java = "java"
  final val JavaIntStream = "IntStream"
  final val JavaRange = "range"
  final val JavaRangeClosed = "rangeClosed"
  final val JavaCompletableFuture = "CompletableFuture"
  final val JavaSupplyAsync = "supplyAsync"
  final val JavaCompletedFuture = "completedFuture"
  final val JavaFailedFuture = "failedFuture"
  final val JavaOptional = "Optional"
  final val JavaAbsent = "absent"
  final val JavaOf = "of"
  final val JavaOfNullable = "ofNullable"
  final val JavaOfEntries = "ofEntries"
  final val JavaOfSupplier = "ofSupplier"
  final val JavaSuccess = "success"
  final val JavaFailure = "failure"

  final val JavaRun = "run"
  final val JavaAccept = "accept"
}