package io.github.effiban.scala2java.core.entities

import scala.meta.XtensionQuasiquoteTerm

object TermSelects {

  final val ScalaPredef = q"scala.Predef"

  final val ScalaArray = q"scala.Array"
  final val ScalaArraySeq = q"scala.collection.immutable.ArraySeq"
  final val ScalaBigDecimal = q"scala.BigDecimal"
  final val ScalaBigInt = q"scala.BigInt"
  final val ScalaBoolean = q"scala.Boolean"
  final val ScalaByte = q"scala.Byte"
  final val ScalaChar = q"scala.Char"
  final val ScalaDouble = q"scala.Double"
  final val ScalaEither = q"scala.Either"
  final val ScalaEquiv = q"scala.Equiv"
  final val ScalaFailure = q"scala.util.Failure"
  final val ScalaFloat = q"scala.Float"
  final val ScalaFunction = q"scala.Function"
  final val ScalaFractional = q"scala.Fractional"
  final val ScalaFuture = q"scala.concurrent.Future"
  final val ScalaHashMap = q"scala.collection.immutable.HashMap"
  final val ScalaHashSet = q"scala.collection.immutable.HashSet"
  final val ScalaIndexedSeq = q"scala.IndexedSeq"
  final val ScalaInt = q"scala.Int"
  final val ScalaIntegral = q"scala.Integral"
  final val ScalaIterable = q"scala.Iterable"
  final val ScalaIterator = q"scala.Iterator"
  final val ScalaLazyList = q"scala.LazyList"
  final val ScalaLinearSeq = q"scala.collection.immutable.LinearSeq"
  final val ScalaListMap = q"scala.collection.immutable.ListMap"
  final val ScalaListSet = q"scala.collection.immutable.ListSet"
  final val ScalaLeft = q"scala.Left"
  final val ScalaList = q"scala.List"
  final val ScalaLong = q"scala.Long"
  final val ScalaMap = q"scala.Predef.Map"
  final val ScalaNil = q"scala.Nil"
  final val ScalaNone = q"scala.None"
  final val ScalaNumeric = q"scala.Numeric"
  final val ScalaOption = q"scala.Option"
  final val ScalaOrdered = q"scala.Ordered"
  final val ScalaOrdering = q"scala.Ordering"
  final val ScalaPartialOrdering = q"scala.math.PartialOrdering"
  final val ScalaPrint = q"scala.Predef.print"
  final val ScalaPrintf = q"scala.Predef.printf"
  final val ScalaPrintln = q"scala.Predef.println"
  final var ScalaRange = q"scala.Range"
  final val ScalaRight = q"scala.Right"
  final val ScalaShort = q"scala.Short"
  final val ScalaSeq = q"scala.Seq"
  final val ScalaSet = q"scala.Predef.Set"
  final val ScalaSome = q"scala.Some"
  final val ScalaSortedMap = q"scala.collection.immutable.SortedMap"
  final val ScalaSortedSet = q"scala.collection.immutable.SortedSet"
  final val ScalaStream = q"scala.Stream"
  final var ScalaString = q"scala.Predef.String"
  final var ScalaStringBuilder = q"scala.StringBuilder"
  final val ScalaSuccess = q"scala.util.Success"
  final val ScalaTreeMap = q"scala.collection.immutable.TreeMap"
  final val ScalaTreeSet = q"scala.collection.immutable.TreeSet"
  final val ScalaTry = q"scala.util.Try"
  final val ScalaVector = q"scala.Vector"
}
